#### [임베딩 이해]

In [1]:
## => Embedding : 고차원 피쳐 ==> 저차원
## => Pytorch : Embedding Layer 제공
##	  * 고정 길이 : Embedding 

In [5]:
## 모듈 로딩
import torch
import torch.nn as nn
import torch.optim as optim

In [6]:
## 임베딩 인스턴스 생성
## -Embedding(입력 딘어사전 크기, 임베딩 크기)
embedding = nn.Embedding(10, 2)

## 임의의 입력 데이터
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])

output = embedding(input)
print(f'INPUNT => \n{input.shape}')
print(f'INPUNT => \n{output.shape}')
print(output[0])

INPUNT => 
torch.Size([2, 4])
INPUNT => 
torch.Size([2, 4, 2])
tensor([[ 0.8788,  1.0020],
        [-1.4029,  1.8842],
        [-0.0813, -1.0056],
        [ 0.8292, -0.6781]], grad_fn=<SelectBackward0>)


In [7]:
# example with padding_idx
embedding = nn.Embedding(10, 3, padding_idx=0)
input = torch.LongTensor([[0, 2, 0, 5]])
embedding(input)

tensor([[[ 0.0000,  0.0000,  0.0000],
         [ 0.6644, -0.1157, -1.9556],
         [ 0.0000,  0.0000,  0.0000],
         [ 1.1923, -0.8622,  0.2506]]], grad_fn=<EmbeddingBackward0>)

In [8]:
# example of changing `pad` vector
padding_idx = 0
embedding = nn.Embedding(3, 3, padding_idx=padding_idx)
embedding.weight
with torch.no_grad():
    embedding.weight[padding_idx] = torch.ones(3)
embedding.weight

Parameter containing:
tensor([[ 1.0000,  1.0000,  1.0000],
        [-0.4578,  0.5787,  0.6917],
        [ 2.2257, -0.5016,  0.6597]], requires_grad=True)